version: 0.1
runson: win

pre:
  - npm ci

matrix:
  os: [win, linux]
  browser: [chrome, firefox]

stages:
  - name: execute_playwright_scenarios
    test:
      # Explicitly command Playwright to look in the tests directory
      - npx playwright test tests/simple_form.spec.ts tests/drag_drop_slider.spec.ts tests/input_form_submit.spec.ts